version: '3'
services:
    opensearch:
        image: opensearchproject/opensearch:latest
        container_name: opensearch
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=StrongPassword123!
            - network.host=0.0.0.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"  # REST API
            - "9600:9600"  # Performance analyzer
